kind: pipeline
type: docker
name: DAFLPipeline

steps:
- name: app-build
  image: plugins/docker:17.12
  settings:
    repo: DAFLDev/DAFLMusic
    auto_tag: true
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push