version: 2.1

jobs:
  "ios":
    macos: 
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Install Flutter SDK Manager
          command: npm install -g fvm
      - run:
          name: Install Flutter SDK
          command: fvm stable && fvm 1.22.5
      - run:
          name: Compile iOS App
          command: cd Sources/dafl_project_flutter/ && flutter build ios --release --no-codesign 
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/*.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app

workflows:
  version: 2
  build:
    jobs:
      - "ios"