version: 2.1

jobs:
  "ios":
    macos: 
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Install Flutter SDK Manager
          command: npm install -g fvm
      - run:
          name: Install Flutter SDK
          command: fvm stable && fvm 1.22.5
      - run:
          name: Compile iOS App
          command: cd Sources/dafl_project_flutter/ && flutter build ios --release --no-codesign

workflows:
  version: 2
  build:
    jobs:
      - "ios"